version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    restart: always
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    expose :
      - 9000
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    restart: always
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver_opts:
      type: none
      o: bind
      device: /home/selkhadr/data/db_data
  wp_data:
    driver_opts:
      type: none
      o: bind
      device: /home/selkhadr/data/wp_data
